### ISSUE TITLE
ENH | rewrite aims_plot

### ISSUE THREAD

**Issue by romankempt** [romankempt/AIMS_tools#2]
- planning to rewrite aims_plot as multi-level typer utility

What does the script need to be able to do?

**Comment by ThomasBrumme** [comment]
Using the command-line interface it would be nice:
- to have more possibilities to personalize the plots (e.g., get rid of the BZ, how to choose colors, so a lot of the options you have within python importing the aimstools)
- to have the current folder as the default choice
- if the script would be less dependent on the order of the input parameters (why does -v needs to be the last?)

**Comment by romankempt** [comment]
Should be addressed with #12. The utilities are now typer-based and should be easier to use and more flexible. But for full control, using python is simply much easier
