### ISSUE TITLE
Mulliken-projected band structure giving artifacts in lines for low number of grid points

### ISSUE THREAD

**Issue by F-Arnold** [romankempt/AIMS_tools#3]
No smooth lines, instead additional horizontal lines for plotting contribution differences similar to plot 3 in code block 2 [here](https://aims-tools.readthedocs.io/en/latest/notebooks/fatbands.html). 
Option `scale_linewidth=False` in `plot()` function doesn't help.
`mode="scatter"` doesn't have enough data points to look good, also warning from matplotlib.

Interpolation of data points needed?

**Comment by romankempt** [comment]
Interpolation was added in #4 amongst many other things. Usage should be easier and I've exposed a bigger part of the source code in the documentation.
